### ISSUE TITLE
Não estou encontrando o cadastro no link

### ISSUE THREAD

**Issue by luizniero** [noharm-ai/brateca#2]
Boa tarde.
Sou estudante de mestrado em ciência da computação na UNESP e estou criando um corpus anotado para a especialidade de psiquiatria.
Eu gostaria muito de ter acesso ao seu corpus, porém não estou encontrando nenhum cadastro/solicitação no link que você colocou no read-me, poderia verificar isso, por favor? Meu e-mail é: luiz.niero@unesp.br

**Comment by heukirne** [comment]
Boa tarde, Luiz.

Não tinha visto seu ticket aqui.
Para ter acesso aos dados, precisa fazer um cadastro no PhysioNet:
https://physionet.org/access-requests/brateca/1.1/

Abraços,
